// This file is auto-generated by scripts/sync-rankings.mjs
// DO NOT EDIT MANUALLY

import game_rakuten_101205 from './game/rakuten-101205.json';
import game_rakuten_565989 from './game/rakuten-565989.json';
import game_rakuten_565990 from './game/rakuten-565990.json';
import game_rakuten_566236 from './game/rakuten-566236.json';
import game_rakuten_566237 from './game/rakuten-566237.json';
import game_yahoo_2161 from './game/yahoo-2161.json';
import game_yahoo_50521 from './game/yahoo-50521.json';
import game_yahoo_50522 from './game/yahoo-50522.json';
import game_yahoo_50798 from './game/yahoo-50798.json';
import game_yahoo_77077 from './game/yahoo-77077.json';

export const RANKING_CACHE = {
  'game/rakuten-101205': game_rakuten_101205,
  'game/rakuten-565989': game_rakuten_565989,
  'game/rakuten-565990': game_rakuten_565990,
  'game/rakuten-566236': game_rakuten_566236,
  'game/rakuten-566237': game_rakuten_566237,
  'game/yahoo-2161': game_yahoo_2161,
  'game/yahoo-50521': game_yahoo_50521,
  'game/yahoo-50522': game_yahoo_50522,
  'game/yahoo-50798': game_yahoo_50798,
  'game/yahoo-77077': game_yahoo_77077,
};
